name: Train Lunar Lander Agent

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y swig  # Required for Box2D
        python -m pip install --upgrade pip
        pip install gymnasium[box2d] numpy argparse

    - name: Train the agent
      run: timeout 6h python train_agent.py --train --filename best_policy.npy

    - name: Upload best policy
      uses: actions/upload-artifact@v4
      with:
        name: best-policy
        path: best_policy.npy
