name: Train Lunar Lander Agent

on:
  workflow_dispatch:  # Runs only when manually triggered

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y swig  # Required for Box2D
        python -m pip install --upgrade pip
        pip install gymnasium[box2d] numpy argparse torch

    - name: Download previous best policy (if available)
      uses: actions/download-artifact@v4
      with:
        name: best-policy
        path: .

    - name: Train the agent (Resume if best_policy.npy exists)
      run: |
        if [ -f "best_policy.npy" ]; then
          echo "Resuming training from best_policy.npy..."
          timeout 5h55m python train_agent.py --train --filename best_policy.npy
        else
          echo "No previous model found. Training from scratch..."
          timeout 5h55m python train_agent.py --train --filename best_policy.npy
        fi

    - name: Upload updated best policy
      uses: actions/upload-artifact@v4
      with:
        name: best-policy
        path: best_policy.npy
